FROM nginx:1.29.4-alpine

# Default Configuration 파일 삭제
RUN rm /etc/nginx/conf.d/default.conf

# Development 설정 파일만 복사
COPY ./config/client-dev.conf /etc/nginx/conf.d/client-dev.conf
COPY ./config/nginx.conf /etc/nginx/nginx.conf

# 로그 디렉토리 생성
RUN mkdir -p /var/log/nginx/client-dev

# Certbot webroot 디렉토리 생성
RUN mkdir -p /var/www/certbot-dev

CMD ["nginx", "-g", "daemon off;"]
