FROM nginx:1.29.4-alpine

# Default Configuration 파일 삭제
RUN rm /etc/nginx/conf.d/default.conf

# Production 설정 파일만 복사
COPY ./config/client-prod.conf /etc/nginx/conf.d/client-prod.conf
COPY ./config/nginx.conf /etc/nginx/nginx.conf

# 로그 디렉토리 생성
RUN mkdir -p /var/log/nginx/client-prod

# Certbot webroot 디렉토리 생성
RUN mkdir -p /var/www/certbot-prod

CMD ["nginx", "-g", "daemon off;"]
